name: Convert Markdown to HTML

on:
  push:
    paths:
      - 'docs/**/*.md'  # Only trigger when Markdown files in 'docs/' change
  workflow_dispatch:  # Allows manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p html_output
          for file in docs/*.md; do
            [ -e "$file" ] || continue  # Skip if no files match
            pandoc -s --template=templates/template.html "$file" -o "html_output/$(basename "${file%.md}.html")"
          done

      - name: Commit and Push HTML files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add html_output/*.html
          git commit -m "Convert Markdown to HTML from docs/" || echo "No changes to commit"
          git push
