name: Convert Markdown to HTML

on:
  push:
    paths:
      - '**.md'  # Run the workflow when any Markdown file is updated
  workflow_dispatch: # Allow manual runs

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p html_output
          for file in *.md; do
            pandoc "$file" -o "html_output/${file%.md}.html"
          done

      - name: Commit and Push HTML files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add html_output/*.html
          git commit -m "Convert Markdown to HTML" || echo "No changes to commit"
          git push
